[project]
name = "dj-store"
version = "0.1.0"
description = "Demo/PoC for vape shop store manager"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "argcomplete>=3.6.2",
    "django>=5.2.4",
]

[dependency-groups]
dev = [
    "ipython>=9.4.0",
]
