# Generated by Django 5.2.4 on 2025-08-03 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Inventory Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sku', models.CharField(help_text='Unique stock keeping unit or barcode', max_length=32, unique=True)),
                ('description', models.TextField(blank=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_in_stock', models.PositiveIntegerField(default=0)),
                ('image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Product category', on_delete=django.db.models.deletion.PROTECT, to='inventory.inventorycategory')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='inventory_i_name_9b5824_idx'), models.Index(fields=['sku'], name='inventory_i_sku_e27286_idx'), models.Index(fields=['category'], name='inventory_i_categor_b07c45_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'category'), name='unique_item_per_category')],
            },
        ),
    ]
