# Generated by Django 5.2.4 on 2025-08-03 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventorycategory_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='inventoryitem',
            name='unique_item_per_category',
        ),
        migrations.RemoveIndex(
            model_name='inventoryitem',
            name='inventory_i_categor_b07c45_idx',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='unit_price',
        ),
        migrations.AlterField(
            model_name='inventorycategory',
            name='display_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitemtype',
            name='category',
            field=models.ForeignKey(help_text='Product category for this item type', on_delete=django.db.models.deletion.PROTECT, to='inventory.inventorycategory'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='item_type',
            field=models.ForeignKey(blank=True, help_text='Group/type this item belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.inventoryitemtype'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['item_type'], name='inventory_i_item_ty_b1f9bd_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(fields=('name', 'item_type'), name='unique_item_per_type'),
        ),
    ]
