# Generated by Django 5.2.4 on 2025-08-03 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryitemtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='item_type',
            field=models.ForeignKey(help_text='Group/type this item belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.inventoryitemtype'),
        ),
    ]
