# Generated by Django 5.2.4 on 2025-08-03 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventoryitem_item_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventoryitem',
            name='unique_item_per_type',
        ),
        migrations.RemoveIndex(
            model_name='inventoryitem',
            name='inventory_i_name_9b5824_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventoryitem',
            name='inventory_i_sku_e27286_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventoryitem',
            name='inventory_i_item_ty_b1f9bd_idx',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='override_category',
            field=models.ForeignKey(blank=True, help_text='Override category if different from item type', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventorycategory'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='override_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override unit price if different from item type', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='item_type',
            field=models.ForeignKey(blank=True, help_text='Optional: link to an item type to inherit price/category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventoryitemtype'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='sku',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='inventoryitemtype',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventorycategory'),
        ),
    ]
