# Generated by Django 5.2.4 on 2025-08-03 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_inventoryitem_unique_item_per_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitemtype',
            options={},
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='override_category',
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='item_type',
            field=models.ForeignKey(help_text='Item type determines category (required)', on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitemtype'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='override_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional override for unit price', max_digits=10, null=True),
        ),
    ]
