# Generated by Django 5.2.4 on 2025-08-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_inventoryitemtype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='display_name',
            field=models.TextField(default='default display name'),
            preserve_default=False,
        ),
    ]
