# Generated by Django 5.2.4 on 2025-08-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventoryitem_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorycategory',
            name='display_name',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='display_name',
            field=models.TextField(max_length=200),
        ),
    ]
