# Generated by Django 5.2.4 on 2025-08-02 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Inventory Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sku', models.CharField(help_text='Unique stock keeping unit or barcode', max_length=32, unique=True)),
                ('category', models.CharField(choices=[('Kratom', 'Kratom'), ('Nitrous', 'Nitrous'), ('Nicotine Juice', 'Nicotine Juice'), ('Vape Device', 'Vape Device'), ('Accessory', 'Accessory'), ('Delta-8', 'Delta-8'), ('Other', 'Other')], default='Other', max_length=32)),
                ('description', models.TextField(blank=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_in_stock', models.PositiveIntegerField(default=0)),
                ('image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_category', models.ForeignKey(blank=True, help_text='Optional custom category if not using predefined ones', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store_mg.inventorycategory')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='store_mg_in_name_a384ad_idx'), models.Index(fields=['sku'], name='store_mg_in_sku_a2a1b7_idx'), models.Index(fields=['category'], name='store_mg_in_categor_fd3a18_idx')],
                'unique_together': {('name', 'category')},
            },
        ),
    ]
